// Generated by CoffeeScript 1.10.0
(function() {
  var Logger, colors,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  colors = require('colors');

  Logger = (function() {
    function Logger() {
      this.Log = bind(this.Log, this);
      this.Info = bind(this.Info, this);
      this.Success = bind(this.Success, this);
      this.Error = bind(this.Error, this);
    }

    Logger.prototype.Error = function(msg) {
      if (typeof msg === 'undefined') {
        return;
      }
      return console.log(("" + msg).red);
    };

    Logger.prototype.Success = function(msg) {
      if (typeof msg === 'undefined') {
        return;
      }
      return console.log(("" + msg).green);
    };

    Logger.prototype.Info = function(msg) {
      if (typeof msg === 'undefined') {
        return;
      }
      return console.log(("" + msg).yellow);
    };

    Logger.prototype.Log = function(msg) {
      if (typeof msg === 'undefined') {
        return;
      }
      return console.log((" - " + msg).green);
    };

    return Logger;

  })();

  module.exports = Logger;

}).call(this);

//# sourceMappingURL=log.js.map
