// Generated by CoffeeScript 1.10.0
(function() {
  var deepMap, fixPathPiece, objTypeof,
    hasProp = {}.hasOwnProperty;

  objTypeof = function(obj) {
    return Object.prototype.toString.call(obj);
  };

  deepMap = function(obj) {
    var dp, k, ref, v;
    dp = deepMap.bind(this);
    if (objTypeof(obj) === "[object Array]") {
      return obj.map(dp);
    } else if (objTypeof(obj) === "[object Object]") {
      for (k in obj) {
        if (!hasProp.call(obj, k)) continue;
        v = obj[k];
        obj[k] = dp(v);
      }
      return obj;
    } else {
      return (ref = typeof this.fn === "function" ? this.fn(obj) : void 0) != null ? ref : obj;
    }
  };

  fixPathPiece = function(piece) {
    return piece.split(/[\/\\?%*:|"<>]/g).filter(function(i) {
      return !!i;
    }).join(" ");
  };

  module.exports = {
    objTypeof: objTypeof,
    deepMap: deepMap,
    fixPathPiece: fixPathPiece
  };

}).call(this);
