// Generated by CoffeeScript 1.10.0
(function() {
  var chkFn, deepMap, fixPathPiece, objTypeof,
    hasProp = {}.hasOwnProperty;

  objTypeof = function(obj) {
    return Object.prototype.toString.call(obj);
  };

  chkFn = function(fn) {
    if (typeof fn === "function") {
      return fn;
    } else {
      return function(o) {
        return o;
      };
    }
  };

  deepMap = function(obj) {
    var dp, k, v;
    dp = deepMap.bind(this);
    if (objTypeof(obj) === "[object Array]") {
      return chkFn(this.array)(obj.map(dp));
    } else if (objTypeof(obj) === "[object Object]") {
      for (k in obj) {
        if (!hasProp.call(obj, k)) continue;
        v = obj[k];
        obj[k] = dp(v);
      }
      return chkFn(this.object)(obj);
    } else {
      return chkFn(this.fn)(obj);
    }
  };

  fixPathPiece = function(piece) {
    return piece.split(/[\/\\?%*:|"<>]/g).filter(function(i) {
      return !!i;
    }).join(" ");
  };

  module.exports = {
    objTypeof: objTypeof,
    deepMap: deepMap,
    fixPathPiece: fixPathPiece
  };

}).call(this);
